apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: eks-hpa
  region: us-west-2

managedNodeGroups:
  - name: my-ng
    instanceType: t2.small
    desiredCapacity: 4
    volumeSize: 8
    iam:
      withAddonPolicies:
        appMesh: true
        albIngress: true