apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-demo-deployment
  labels:
    app: flask-demo  
spec:
  selector:
    matchLabels:
      app: flask-demo
  replicas: 4 
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: flask-demo
    spec:
      containers:
      - name: flask-demo
        image: 792300178540.dkr.ecr.us-west-2.amazonaws.com/wkacz:2.0.0
        ports:
        - containerPort: 8000
        imagePullPolicy: Always


# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: nginx-deployment
#   labels:
#     app: nginx
# spec:
#   replicas: 4
#   selector:
#     matchLabels:
#       app: nginx
#   strategy:
#     type: RollingUpdate
#     rollingUpdate:
#       maxSurge: 1
#       maxUnavailable: 1
#   template:
#     metadata:
#       labels:
#         app: nginx
#     spec:
#       containers:
#       - name: nginx
#         image: 792300178540.dkr.ecr.us-west-2.amazonaws.com/wkacz:2.0.0
#         ports:
#         - containerPort: 80